// <auto-generated />
namespace OneDriveFinal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class INITIAL_MIGRATION : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(INITIAL_MIGRATION));
        
        string IMigrationMetadata.Id
        {
            get { return "201809131450467_INITIAL_MIGRATION"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
